# Generated by Django 6.0.6 on 2026-06-18 02:57

import django.contrib.gis.db.models.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('time_caught', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatchPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('route', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('type', models.CharField(choices=[('STATIONARY', 'Stationary'), ('ROVING', 'Roving'), ('ACTIVE', 'Active')], default='STATIONARY', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('FRIENDS', 'Friends Only'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('distance_walked_meters', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSpeciesStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_caught', models.IntegerField(default=0)),
            ],
        ),
    ]
