# Generated by Django 6.0.6 on 2026-06-18 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catchphoto',
            name='catch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='fishing.catch'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='fishing.session'),
        ),
        migrations.AddField(
            model_name='catch',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.species'),
        ),
        migrations.AddField(
            model_name='userspeciesstats',
            name='first_catch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fishing.catch'),
        ),
        migrations.AddField(
            model_name='userspeciesstats',
            name='max_length_catch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fishing.catch'),
        ),
        migrations.AddField(
            model_name='userspeciesstats',
            name='max_weight_catch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fishing.catch'),
        ),
        migrations.AddField(
            model_name='userspeciesstats',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.species'),
        ),
        migrations.AddField(
            model_name='userspeciesstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='catch',
            index=models.Index(fields=['location'], name='fishing_cat_locatio_7e76e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userspeciesstats',
            unique_together={('user', 'species')},
        ),
    ]
