# Generated by Django 6.0.6 on 2026-06-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='time_caught',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='catchphoto',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
