# Generated by Django 6.0.6 on 2026-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0003_alter_catch_time_caught_alter_catchphoto_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='distance_walked_meters',
        ),
        migrations.RemoveField(
            model_name='session',
            name='route',
        ),
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
